language: node_js
node_js:
- '8'
branchs:
  only:
  - master
install:
- npm install
script:
- npm run build
cache:
  directories:
  - node_modules
addons:
  ssh_known_hosts:
  - 39.108.170.7
after_success:
- chmod 600 ~/.ssh/jianshu
- echo -e "User root\n\tHost jianshu\n\tHostName 39.108.170.7\n\tPort 22\n\tIdentityFile
  ~/.ssh/jianshu\n\tProtocol 2\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
- chmod 644 ~/.ssh/config
- scp -r build jianshu:/usr/home/wwwroot/
- ssh jianshu 'cd /usr/home/wwwroot/ && rm -rf spa && mv build spa'
before_install:
- openssl aes-256-cbc -K $encrypted_23e9a859447d_key -iv $encrypted_23e9a859447d_iv
  -in jianshu.enc -out ~\/.ssh/jianshu -d
