export const SEARCH_FOCUS = "search_focus"
export const SEARCH_BLUR = "search_blur"
export const SEARCH_LIST = "search_list"
export const CHANGE_LIST = "change_list"
export const MOUSE_ENTER = "mouse_enter"
export const MOUSE_LEAVE = "mouse_leave"